[platformio]
src_dir = src

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
build_src_filter = +<esp32/> -<esp01s/>

[env:esp01s]
platform = espressif8266
board = esp01_1m
framework = arduino
upload_speed = 115200
monitor_speed = 115200
board_build.flash_mode = dout
build_src_filter = +<esp01s/> -<esp32/>
